"""Add version for file

Revision ID: 1089851185ab
Revises: 6d8ecffec2cc
Create Date: 2024-10-26 05:44:04.749137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '1089851185ab'
down_revision: Union[str, None] = '6d8ecffec2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'storage_files',
        sa.Column(
            'version', sa.Integer(), nullable=False, default=1, server_default="1"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_files', 'version')
    # ### end Alembic commands ###
