"""Add based_on for file

Revision ID: 88a55e447b68
Revises: 1089851185ab
Create Date: 2024-10-27 06:42:49.069114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '88a55e447b68'
down_revision: Union[str, None] = '1089851185ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_files', sa.Column('based_on_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'storage_files', 'storage_files', ['based_on_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storage_files', type_='foreignkey')
    op.drop_column('storage_files', 'based_on_id')
    # ### end Alembic commands ###
