"""Remove uniq filename

Revision ID: f2d6e951a4f2
Revises: 909aeef40303
Create Date: 2024-09-09 13:12:22.369685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f2d6e951a4f2'
down_revision: Union[str, None] = '909aeef40303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('storage_files_filename_key', 'storage_files', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('storage_files_filename_key', 'storage_files', ['filename'])
    # ### end Alembic commands ###
